info:
  app:
    name: Spring Batch TRE BR Boletim Urna
    version: 1.0.0
    
logging:
  level:
    root: WARN
    '[org.springframework.web]': WARN
    '[com.gbvbahia]': DEBUG    
    
   
app:
  batch:
    threads:
      chunks: 5 
      amount: 10 

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
      isolation-level-for-create: default
  flyway:
    baselineOnMigrate: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 20
    driver-class-name: org.postgresql.Driver
    url: #By profile
    username: #By profile
    password: #By profile
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    #Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
    properties:
      hibernate:
        temp:
          '[use_jdbc_metadata_defaults]': false  